---
hostname_configure: false
firewall_enabled: false
installed_extras:
  - adminer
  - drupalconsole
  - drush
  - java
  - nodejs
  - redis
  - mailhog
  - memcached
  - pimpmylog
  - solr
  - varnish

# Don't build or install Drupal inside the container.
drupal_build_makefile: false
drupal_build_composer: false
drupal_build_composer_project: false
drupal_install_site: false

extra_packages:
  - rsync
  - sqlite
  - vim

mysql_max_connections: 200
mysql_max_allowed_packet: 2048M
mysql_query_cache_limit: 1024M
mysql_query_cache_size: 256M
mysql_query_cache_type: 1
mysql_innodb_buffer_pool_size: 128M
mysql_innodb_flush_method: O_DIRECT

php_apc_shm_size: "1024M"
php_memory_limit: "4096M"
php_upload_max_filesize: "4096M"
php_post_max_size: "4096M"

solr_version: "7.7.2"
solr_xms: "1024M"
solr_xmx: "2048M"

mgmt_install_dir: /var/www/pacifica-mgmt/pacifica-metadata-mgmt-0.3.0/build

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "mgmt.{{ vagrant_hostname }}"
    documentroot: "{{ mgmt_install_dir }}"
    extra_parameters: |
      <Location /mdapi>
        ProxyPass http://localhost:8121/
        ProxyPassReverse http://localhost:8121/
        Require all granted
      </Location>

apache_mods_enabled:
  - expires.load
  - headers.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
  - proxy_http.load
